### ISSUE TITLE
Strange behavior with RPC delay 55

### ISSUE THREAD

**Issue by andrich48** [IllidanS4/pcsconv#2]
Release - pcsconv 1.2
OS - Windows 7 x64
During capturing and editing game sound, i've met strange condition - utility sometimes does not work with '55' delay.
I completely dont know that RPC syntax, so I have no idea is my sequence valid or not.
Here is an example when pcsconv works with 50, 60, (any other) delay but doesnt work with magic '55' number.

```
D:\Games\dosbox\pcsconv>type cat.rpc3.txt
SetCountdown: 5000
Delay: 50
D:\Games\dosbox\pcsconv>pcsconv.exe -in txt -out play cat.rpc3.txt test.wav
pcsconv 1.2 (c) 2013 - 2016 by IllidanS4@gmail.com
test.wav
00:00:00.0500000
Creating WAV...
Playing...
D:\Games\dosbox\pcsconv>type cat.rpc3.txt
SetCountdown: 5000
Delay: 55
D:\Games\dosbox\pcsconv>pcsconv.exe -in txt -out play cat.rpc3.txt test.wav
pcsconv 1.2 (c) 2013 - 2016 by IllidanS4@gmail.com
test.wav
00:00:00.0550000
Creating WAV...

Необработанное исключение: System.IndexOutOfRangeException: Индекс находился вне
 границ массива.
   в IllidanS4.Wave.WaveSong.WriteSamples(Int32 sampleRate, Double[] samples)
   в IllidanS4.Wave.WaveBase.GetSamplesDouble(Int32 sampleRate)
   в IllidanS4.Wave.SampledBase.GetSamplesInt16(Int32 sampleRate)
   в IllidanS4.Wave.SampledBase.GetSamples(Int32 sampleRate, TypeCode format)
   в IllidanS4.Wave.SampledBase.GetSamples[T](Int32 sampleRate)
   в speakerconv.SaveWAV.CreateSong(IList`1 data, WaveFunction waveType, Double
volume, Boolean clip, Int32 frequency)
   в speakerconv.PlayWAV.ProcessFile(OutputFile file, ConvertOptions options)
   в speakerconv.OutputProcessor.ProcessFiles(IEnumerable`1 files, ConvertOption
s options)
   в speakerconv.Program.ProcessInput(ConvertOptions options)
   в speakerconv.Program.Main(String[] args)
D:\Games\dosbox\pcsconv>type cat.rpc3.txt
SetCountdown: 5000
Delay: 60
D:\Games\dosbox\pcsconv>pcsconv.exe -in txt -out play cat.rpc3.txt test.wav
pcsconv 1.2 (c) 2013 - 2016 by IllidanS4@gmail.com
test.wav
00:00:00.0600000
Creating WAV...
Playing...
```

Also, there are moments when magic '55' delay does work and when doesnt.
See my files attached, one of them contains lots of '55' delays and works, other contains lots of '55' delays and does not work.
What am I doing wrong and where is the problem?

[cat.error.txt](https://github.com/IllidanS4/pcsconv/files/531484/cat.error.txt)
[cat.works.txt](https://github.com/IllidanS4/pcsconv/files/531485/cat.works.txt)

**Comment by IS4Code** [comment]
Thanks for the notification, but I am already aware of this issue. Your syntax is correct, but there are some rounding issues from the latest update that cause this. An older version should work. I am already testing the fixes, which will be comitted soon.

**Comment by IS4Code** [comment]
New version with the fix uploaded. Should work.

**Comment by andrich48** [comment]
Thanks! Right now I cannot reproduce this problem, it seems to be fixed.
I will check it more later. There are some other problems (will open a new issue).

**Comment by andrich48** [comment]
P.S. There still are some problems with 'Alley Cat' game.
Intro theme works ok (recorded and converted to any format), but during in-game process there are glitches, especially in main screen (alley):
1. launched with 'dosbox -console' parameters, alley soundtrack sounds like some notes are skipped, i just dont hear any soundtrack, only some clicks.
I have Windows 7 x64, quad-core CPU@2Ghz, SSD drive. I dont think this can be related to slow performance.
2. After conversion from pcs to rpc, resulting file has many sequences like this:
`SetCountdown: 408
SetCountdown: 499
SetCountdown: 416
SetCountdown: 436
SetCountdown: 400
SetCountdown: 538
SetCountdown: 418
SetCountdown: 408
SetCountdown: 400
SetCountdown: 404
SetCountdown: 532
SetCountdown: 581
SetCountdown: 460
SetCountdown: 595
SetCountdown: 466
SetCountdown: 608
SetCountdown: 416
SetCountdown: 477
SetCountdown: 466
SetCountdown: 404
Delay: 1`
If you run Alley Cat on latest DOSBox 0.74, you can hear that alley soundtrack really consists of short low-tone notes, like clicks.
Can you check this, please? I can attach my Alley Cat game if needed.

**Comment by IS4Code** [comment]
Based on Alley Cat videos on YouTube, the game was probably intended to play only clicks on the main screen. Maybe they are related more to sounds of the game objects than to some music, so that's why I haven't uploaded them on SpeakerSoundtracks. Does the output of pcsconv correspond with the sound DOSBox plays? If so, I won't be probably able to fix it. You may want to hear it on real hardware, if you think it would sound better.

**Comment by andrich48** [comment]
No, it doesnt.
Non-modified DOSBox plays all sound as it should.
Modified DOSbox skips some notes during gameplay (i dont hear them).
pcsconv output skips even more notes (about 10% of Modified DOSBox gameplay sound).
It was not game objects interaction sound, it was music made from clicks.

**Comment by IS4Code** [comment]
Now I see that indeed there is some music in the main game screen, but I am not sure that the modified DOSBox would not play it. I have recorded the game in both versions of DOSBox, so you can compare:
Original version: https://youtu.be/VPDJamKY0bY
Modified version: https://youtu.be/3HhAmpIXMvA
This stdout file corresponds with the second version: [cat.zip](https://github.com/IllidanS4/pcsconv/files/533341/cat.zip).
Now I don't hear any notes missing in the modified DOSBox version, and there shouldn't really be a reason for it, because the only thing I have modified in the sources is precisely outputting the information sent to PC Speaker ports, and nothing more. The only possibility was that I either grabbed wrong sources, or that the method I compiled it produced some errors in the result (and it did, right when you try to close DOSBox). Please compare the two videos and point me to some differences in the music there.

As for the output of pcsconv, it certainly does omit some sounds from the result. If you inspect and compare the waves, there are two types of the omitted sounds: a) the shortest clicks possible - half of a single square wave period, and noises. Both of them are not rendered at all. The reason for the clicks is simple - they are shorter than a millisecond, thus not representable in the PCS-STDOUT format. I guess they are regarded as a zero-length wave and are removed at some point in the rendering process. The noises are a standard example of a non-standard means of accessing the PC Speaker, and these are supported only to a limited extent. The PC Speaker can be abused for producing more complex sounds, like noises, FM synthesised sounds or samples, and my tools work only for standard musical beeps. Even DOSBox renderding is not 100% accurate in rendering these sounds, but there are some builds with better support.

The noises etc. aren't possible to store and render via the current formats and methods, and they'll probably never be. But the clicks are a standard way of manipulating the PC Speaker, only that they are too short to be faithfully recorded. But there is a simple way to handle it - make a special case for zero-length waves, and render them with a given length. I think I will be able to accomplish that. Expect the fix soon. ☺

**Comment by IS4Code** [comment]
[pcsconv.zip](https://github.com/IllidanS4/pcsconv/files/533486/pcsconv.zip)

Please test this version if it renders the clicks correctly. I have added the "--clicks" parameter that handles zero-length waves and sets their length. It has an argument that works differently whether the output is WAV or DRO. For WAV, it represents a multiple of the wave period, so "--clicks 0.5" is exactly what is seen in Alley Cat - one single "ridge" of the wave. For DRO, it represents the actual length of the click in whole milliseconds, so "--clicks 1" makes all zero-length waves 1ms-long waves. If you forget the parameter, the application reminds you to add it, as it does for "--sanitize".

**Comment by andrich48** [comment]
> Now I don't hear any notes missing in the modified DOSBox version, and there shouldn't really be a reason for it, because the only thing I have modified in the sources is precisely outputting the information sent to PC Speaker ports, and nothing more.
> As for the output of pcsconv, it certainly does omit some sounds from the result. 

pcsconv is only conversion utility from PCS (raw output from DOSBox) to RPC and other formats, right?
So, DOSBox generates all output (including noise and wav/mp3 through pc speaker output), but pcsconv later strips some data, right?

> The reason for the clicks is simple - they are shorter than a millisecond, thus not representable in the PCS-STDOUT format. I guess they are regarded as a zero-length wave and are removed at some point in the rendering process.

Very short notes are not representable even in **DOSBox PCS-STDOUT** format,? i.e. they are stripped even from 'stdout.txt' and there is no way to get them?

> Even DOSBox renderding is not 100% accurate in rendering these sounds, 

I tried to make an exact comparison and got a fantastic result,
I've recorded main alley soundtrack in wav file with three methods:
1. DOSBox 0.65 - default 'wav capture' engine (Ctrl+Alt+F6)
2. Modified DOSBox - default 'wav capture' engine (Ctrl+Alt+F6)
3. Modified DOSBox PCS - pcsconv pcs2wav conversion 
`pcsconv.exe -in pcs -out wav --clicks 0.5 cat.pcs.txt test.wav`
...And compared resulting wav files in audio editor (SoundForge).
[https://s16.postimg.org/i6y58939x/comparison.jpg](url)
Result was different for every method! Sometimes pcsconv-generated wav was even better than Modified DOSBox wav capture and better than DOSBox 0.65 capture. Sometimes DOSBox 0.65 capture was better.
P.S. I also did manual normalization and some notes are shorter (quieter) than others but you still can clearly see which notes are present and which notes are not present. I've also added some manual painting - green and red lines.

So, if this is true, even DOSBox with wav recording is not able to capture every short click.
![comparison](https://cloud.githubusercontent.com/assets/17713654/19489291/56ba169c-9573-11e6-8cab-518acd34e9ee.jpg)

**Comment by IS4Code** [comment]
The PCS format is really quite similar to the RPC format. It logs all that that are sent to ports related to the PC Speaker, with the port number, state, value, and current time in milliseconds. If the changes are closer than a millisecond, they are regarded as immediate, and may be ignored without the "--clicks" options. In some cases, even DOSBox may ignore those short changes. But the format can still log all PC Speaker changes, so even clicks not rendered by DOSBox. I am quite glad that my tool performs better than DOSBox in some cases. All in all, it's not meant to be an accurate PC Speaker representation.
